aws_region         = "us-east-1"
domain             = "pantrytrak.app"
hosted_zone_domain = "_amazonses.pantrytrak.app"
hosted_zone_id     = "Z0692044153KCOIH7CFJ"
from_email         = "contact@pantrytrak.app"
to_email           = "artanmuzhaqi@gmail.com"
